# the next line tells wekatester to report only latency.
# report latency
[fio-latency-00]
description='wekatester latency workload'
readwrite=randrw
rwmixread=100
blocksize=4ki
iodepth=1
iodepth_batch=1
iodepth_batch_complete=1
numjobs=1
time_based=1
runtime=20
ramp_time=5
group_reporting=1
norandommap=1
randrepeat=0
ioengine=posixaio
nrfiles=1
filesize=1G
create_serialize=0
direct=1
directory=/mnt/wekatester
filename_format=$jobname/$jobnum/$filenum
