# the next line tells wekatester to report only iops.
# report iops
[fio-iops-00]
description='wekatester iops workload'
readwrite=randread
blocksize=4k
iodepth=128
iodepth_batch=16
iodepth_batch_complete=16
numjobs=20
time_based=1
runtime=20
ramp_time=5
group_reporting=1
norandommap=1
randrepeat=0
ioengine=posixaio
nrfiles=20
filesize=9m-11m
openfiles=100
file_service_type=normal
create_serialize=0
direct=1
directory=/mnt/wekatester
filename_format=$jobname/$jobnum/$filenum
